package com.lindar.braintree.enums;

public enum TransactionStatus {
    AUTHORIZATION_EXPIRED,
    AUTHORIZED,
    AUTHORIZING,
    FAILED,
    GATEWAY_REJECTED,
    PROCESSOR_DECLINED,
    SETTLED,
    SETTLEMENT_CONFIRMED,
    SETTLEMENT_DECLINED,
    SETTLEMENT_PENDING,
    SETTLING,
    SUBMITTED_FOR_SETTLEMENT,
    UNRECOGNIZED,
    VOIDED;
}
